# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.naruto.ssm.springMVC_practise.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 访问Knife4j的文档地址
# http://127.0.0.1:8080/doc.html#/home
# 访问swagger的文档地址
# http://127.0.0.1:8080/swagger-ui/index.html