server:
  port: 8848

spring:
  application:
    name: ioc
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_study
    username: root
    password: 123456

attribute:
  name: 你好
