# tomcat服务
server:
  port: 8888

# spring配置
spring:
  application:
    name: SpringBoot
  profiles:
    active: common-one
    #    include: common  # 引用其他配置文件，配置文件名必须相同
    group: # 配置分组（环境隔离）
      common-one:
#        - test
        - common
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-example
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource   # 配置文件中配置数据库连接池类型；  也可以自己定义配置类
  banner:
    location: classpath:banner.txt

# 可观测性actuator监控，访问地址：http://localhost:8888/actuator
management:
  endpoints:
    web:
      exposure:
        #暴露所有端点
        include: "*"


# SpringBoot 默认使用 slf4j + logback
# 日志配置
logging:
  # 日志分组
  group:
    biz: com.study.springboot.controller, com.study.springboot.service  # biz自定义的分组名
  # 日志级别
  level:
    root: info  # 日志输出级别
    com.study.springboot.LogTest: trace  # 指定包日志输出级别，包用全类名
    biz: debug   # 日志分组，设置日志级别
  # 将日志输出到指定文件
  file:
    name: SpringBootStudy.log  # 当前项目所在的根文件夹下生成一个 指定名字的 日志文件
  #    path: D://springbootLog # 日志文件保存路径，会生成一个spring.log的日志文件
  # 若是name与path都配置，那么name的优先级更高，会采用name的配置

  # 日志归档与切割
  # 归档：创建一个归档文件，将当前日志文件重命名，并保存到指定位置；
  # 切割：每个文件4MB，超过大小切割成另一个文件
  logback:
    rollingpolicy:
      max-file-size: 1MB  # 文件大小
      max-history: 5 # 日志文件保存的最大天数
      total-size-cap: 500MB  # 总大小，日志文件被删除前，可以容纳的最大值（默认值：0B【不限制大小】）
      #      file-name-pattern: springboot-%d{yyyy-MM-dd}.log  # 日志归档的文件名格式
      clean-history-on-start: false  # 应用启动时，是否清理以前的日志文件，默认值：false






dog:
  name: 泰迪
  age: 12
  sex: 男

# yaml语法格式
person:
  name: 李华
  age: 18
  birthDay: 1999/01/01
  like: true
  child:
    name: 小明
    age: 3
    birthDay: 2018/01/01
    text: [ 文本4, 文本5, 文本6 ]   # 集合的两种写法，1、[属性值1, 属性值2, ...]；2、- 属性值
  #      - 文本1
  #      - 文本2
  #      - 文本3
  dogs:
    - name: 旺财
      age: 3
    - name: 旺财2
      age: 4
    - { name: 旺财3, age: 5 }
  cats:
    redCat:
      name: 招财猫
      age: 3
    blackCat:
      name: 招财猫2
      age: 4
    yellowCat:
      name: 招财猫3
      age: 5
