server:
  port: 8848

spring:
  application:
    name: MyBatis

  #  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-example?allowMultiQueries=true # allowMultiQueries开启批量操作，开启mysql8.0以上版本支持，否则会报错
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    aggressive-lazy-loading: false  # 关闭立即加载
    lazy-loading-enabled: true # 开启懒加载

# 开启日志
logging:
  level:
    com.naruto.mybatis.mapper: debug

